language: cpp
compiler:
  - gcc
# - clang
before_install:
  - sudo apt-get install -qq libboost-dev liblua5.1-0-dev libxy-dev
before_script:
  - autoreconf -i
script: ./configure --disable-GUI LUA=/usr/bin/lua5.1 LUA_INCLUDE=-I/usr/include/lua5.1 LUA_LIB=-llua5.1 && make
branches:
  only:
    - master
notifications:
  recipients:
    - wojdyr@gmail.com
  email:
    on_success: change
    on_failure: always
